# Generated by Django 5.2 on 2025-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_cards', '0002_reviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhistory',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
