# Generated by Django 5.2 on 2025-04-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_cards', '0004_flashcard_next_review_date_alter_flashcard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='next_review_date',
        ),
    ]
